name: STM8s Docker CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ stm8s ]
  #pull_request:
  #  branches: [ stm8s ]

env:
  GHC_REGISTRY: ghcr.io
  GHC_IMAGE_NAME: ${{ github.repository }}
  DOCKER_IMAGE_NAME: panoti/sdcc


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.GHC_REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.GHC_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to DockerHub
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.GHC_REGISTRY }}/${{ env.GHC_IMAGE_NAME }},${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/bake-action@v1
        with:
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./stm8s/docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: build
